### ISSUE TITLE
Race condition on run command

### ISSUE THREAD

**Issue by seblj** [seblj/cargo-aoc#50]
Since we capture stdout from running the aoc day and printing it from here, it is getting cluttered with the output from stderr that we don't capture.

Need to find a way to merge these and print stdout and stderr in correct order. One possible solution could be to use the `duct` crate

**Comment by sivertjoe** [comment]
Do you have a concrete way to replicate the race condition?

**Comment by seblj** [comment]
What I did to easy replicate it was to do something like this:

```rs
let mut i = 0;
loop {
    let duration = tokio::time::Duration::from_secs(2);
    println!("stdio 1: {}", i);
    eprintln!("stderr 2: {}", i);
    println!("stdio 3: {}", i);
    eprintln!("stderr 4: {}", i);
    println!("stdio 5: {}", i);
    eprintln!("stderr 6: {}", i);
    println!("stdio 7: {}", i);
    eprintln!("stderr 8: {}", i);
    println!("stdio 9: {}", i);
    tokio::time::sleep(duration);
    i += 1;
}
```

**Comment by sivertjoe** [comment]
Let use duct then.
The things that _need_ to changed are:
1. Use the cmd! instead of Command in run
2. Fix submit feature.

For #2, we should be _a_ _bit_ careful. For instance imagine that I print "hello" 1_000_000 times, and push this onto the out string, e.g, 

```rs
 while let Some(Ok(line)) = lines.next()
 {
     println!("{}", line);
     out.push_str(&line);  // <----------- this line
     out.push('\n');
}
```
it could take a lot of time/memory. We should only push lines on the "({}ms)	Task one: {}" format.

Thing that maybe _should_ be changed?
Every other call to a Command, to be consistent?

Let me know what you think

**Comment by seblj** [comment]
Yes, good catch with pushing to the string! I'll try to fix it tomorrow!

I don't really have a preference on using `duct` for everything🤷‍♂️ Positive side is that it is consistent, but negative is that it is not async. But is it really a big deal that it is not async?
